#!/bin/bash

DIR="$PWD"
PLUGINS="$PWD/plugins/"
TMP="$(mktemp -d -t server-essentials)"

[ -d "$PLUGINS" ] || mkdir ./plugins/

trap "fail Cancelled install" SIGINT

# Utility methods
fail() {
    taskfail
    clean

    echo -e "\n$(tput setaf 1)Error: $(tput sgr0)$@"
    exit 1
}

clean() {
    rm -fr "$TMP"
}

configure() {
    cd "$DIR"
    [ -f eula.txt ] || echo "eula=true" > eula.txt

    echo '#!/bin/bash
cd "$(dirname "$0")"
java -Xmx4G -jar spigot-*.jar' > start.sh
    chmod +x start.sh
}

# Task methods
task() {
    echo -en "$(tput setaf 3)»$(tput sgr0) $(tput bold)$@$(tput sgr0) "
}

taskdone() {
    echo -en "\r$(tput setaf 2)✔$(tput sgr0)\n"
}

taskfail() {
    echo -en "\r$(tput setaf 1)✖$(tput sgr0)\n"
}

# Download methods
get-file() {
    curl -fsSL "$1" -o "$2" 2> /dev/null || return 1
}

jenkins() {
    task "Installing $1 from $2"

    cd "$TMP"
    mkdir "$1" && cd "$1" || fail "Failed to create folder for $1"
    get-file "$2/job/$1/lastSuccessfulBuild/artifact/*zip*/archive.zip" all.zip || fail "Failed to download $1 from $2"
    unzip all.zip > /dev/null && mv ./archive/* . && rm -fr ./archive/ || fail "Failed to unzip $1"

    shift 2
    OUTPUT="$1"
    shift

    for folder in $@; do
        mv ./"$folder"/*.jar "$OUTPUT"
    done

    taskdone
}

bukkit() {
    task "Installing $1"

    cd "$TMP"
    mkdir "$1" && cd "$1" || fail "Failed to create folder for $1"
    get-file "https://dev.bukkit.org/projects/$2/files/latest" "$1.jar" || fail "Failed to download $1"
    mv ./*.jar "$PLUGINS"

    taskdone
}



###########################################################################
##################### ACTUALLY DOWNLOAD SOME CRAP NOW #####################
###########################################################################



jenkins Spigot "http://ci.getbukkit.org" "$DIR" .
jenkins EssentialsX "https://ci.drtshock.net" "$PLUGINS" Essentials/target EssentialsChat/target
jenkins ProtocolLib "http://ci.dmulloy2.net" "$PLUGINS" modules/ProtocolLib/target

bukkit PlugMan plugman
bukkit PermissionsEx permissionsex
bukkit Vault vault
bukkit WorldEdit worldedit
bukkit WorldGuard worldguard

task "Installing Multiverse"
get-file "https://dev.bukkit.org/projects/multiverse-core/files/912081/download" "$PLUGINS/Multiverse-Core-2.5-b717.jar" || fail "Failed to install Multiverse-Core"
get-file "https://dev.bukkit.org/projects/multiverse-netherportals/files/772769/download" "$PLUGINS/Multiverse-NetherPortals-2.5.jar" || fail "Failed to install Multiverse-NetherPortals"
taskdone

task "Configuring"; configure; taskdone
task "Cleaning up"; clean; taskdone



###########################################################################
#################### ALL DONE NOW, NOTHING TO SEE HERE ####################
###########################################################################



echo "$(tput smul)$(tput setaf 2)$(tput bold)
Server setup complete. You can run the server with ./start.sh
$(tput rmul)$(tput sgr0)"

sleep 1